/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import javax.swing.JOptionPane;
import koneksi.UserSession;

public class Login extends javax.swing.JFrame {
    String user="",pass="";
    private final Connection conn = new koneksi().connect();
    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        ImageIcon img = new ImageIcon("src/icon/logo.png");
        this.setIconImage(img.getImage());
        initUI();
    }
    
    private void initUI(){ 
        getContentPane().setBackground(new Color(245, 245, 245));
        
        Dimension windowSize = getSize();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Point centerPoint = ge.getCenterPoint();
        int dx = centerPoint.x - windowSize.width / 2;
        int dy = centerPoint.y - windowSize.height / 2;    
        setLocation(dx, dy);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Siswa = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        submit_siswa = new javax.swing.JButton();
        nisn = new javax.swing.JTextField();
        Petugas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tuser = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        tpass = new javax.swing.JPasswordField();
        kepalasekolah = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        submit_kepalasekolah = new javax.swing.JButton();
        nip = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N

        Siswa.setBackground(new java.awt.Color(217, 217, 217));
        Siswa.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        jLabel6.setText("NISN SISWA");

        submit_siswa.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 11)); // NOI18N
        submit_siswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/login.png"))); // NOI18N
        submit_siswa.setText("MASUK");
        submit_siswa.setBorder(null);
        submit_siswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit_siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_siswaActionPerformed(evt);
            }
        });

        nisn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nisn.setBorder(null);
        nisn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nisn.setOpaque(false);

        javax.swing.GroupLayout SiswaLayout = new javax.swing.GroupLayout(Siswa);
        Siswa.setLayout(SiswaLayout);
        SiswaLayout.setHorizontalGroup(
            SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nisn)
                    .addGroup(SiswaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 190, Short.MAX_VALUE))
                    .addComponent(submit_siswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SiswaLayout.setVerticalGroup(
            SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SiswaLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nisn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(submit_siswa, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Login Siswa", Siswa);

        Petugas.setBackground(new java.awt.Color(217, 217, 217));
        Petugas.setOpaque(false);
        Petugas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        jLabel2.setText("Username");
        Petugas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        jLabel3.setText("Password");
        Petugas.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 131, -1, -1));

        tuser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tuser.setBorder(null);
        tuser.setOpaque(false);
        Petugas.add(tuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 79, 331, 46));

        submit.setBackground(new java.awt.Color(255, 255, 255));
        submit.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 11)); // NOI18N
        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/login.png"))); // NOI18N
        submit.setText("MASUK");
        submit.setBorder(null);
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.setOpaque(false);
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        Petugas.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 235, 331, 48));

        jCheckBox1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jCheckBox1.setText("LIHAT");
        jCheckBox1.setOpaque(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        Petugas.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 171, -1, 46));

        tpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tpass.setText("PASSWORD");
        tpass.setBorder(null);
        tpass.setOpaque(false);
        tpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpassActionPerformed(evt);
            }
        });
        Petugas.add(tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 170, 270, 46));

        jTabbedPane1.addTab("Login Petugas", Petugas);

        kepalasekolah.setBackground(new java.awt.Color(217, 217, 217));
        kepalasekolah.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        jLabel8.setText("NIP");

        submit_kepalasekolah.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 11)); // NOI18N
        submit_kepalasekolah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/login.png"))); // NOI18N
        submit_kepalasekolah.setText("MASUK");
        submit_kepalasekolah.setBorder(null);
        submit_kepalasekolah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit_kepalasekolah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_kepalasekolahActionPerformed(evt);
            }
        });

        nip.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nip.setBorder(null);
        nip.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nip.setOpaque(false);

        javax.swing.GroupLayout kepalasekolahLayout = new javax.swing.GroupLayout(kepalasekolah);
        kepalasekolah.setLayout(kepalasekolahLayout);
        kepalasekolahLayout.setHorizontalGroup(
            kepalasekolahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kepalasekolahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kepalasekolahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nip)
                    .addGroup(kepalasekolahLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 293, Short.MAX_VALUE))
                    .addComponent(submit_kepalasekolah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        kepalasekolahLayout.setVerticalGroup(
            kepalasekolahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kepalasekolahLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nip, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(submit_kepalasekolah, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Login Kepala Sekolah", kepalasekolah);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 360, 360));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/2.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        String ObjButton[] = {"YES","NO"};
        int pilihan = JOptionPane.showOptionDialog(null,"Apakah Anda yakin ingi keluar?","Message", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
            null,ObjButton,ObjButton[1]);
        if(pilihan == 0){
            dispose();
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void tpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpassActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()){
            tpass.setEchoChar((char)0);
        }else{
            tpass.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        user = tuser.getText();
        pass = tpass.getText();

        String sql = "select * from petugas where username='"+user+"'and password='"+pass+"';";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            if(hasil.next()){
                String id = hasil.getString("id_petugas");
                String namapetugas = hasil.getString("nama_petugas");

                //set user data session
                UserSession.set_nisn(id);
                UserSession.set_nama_siswa(namapetugas);

                JOptionPane.showMessageDialog(null, "Selamat datang "+ namapetugas +" !");
                new petugas. menupetugas().setVisible(true);
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null, "LOGIN GAGAL");
                tuser.setText("");
                tpass.setText("");
                tuser.requestFocus(true);
            }
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "LOGIN GAGAL"+e);

        }
    }//GEN-LAST:event_submitActionPerformed

    private void submit_siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_siswaActionPerformed
        String Get_nisn = nisn.getText();
        String sql = "select * from siswa where nisn='"+Get_nisn+"';";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(sql);

            if (rs.next()) {
                String nisn = rs.getString("nisn");
                String namasiswa = rs.getString("namasiswa");

                //set user data session
                UserSession.set_nisn(nisn);
                UserSession.set_nama_siswa(namasiswa);

                JOptionPane.showMessageDialog(null, "Selamat datang "+ namasiswa +" !");
                new siswa. menusiswa().setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "NISN tidak ditemukan");
            }

        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_submit_siswaActionPerformed

    private void submit_kepalasekolahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_kepalasekolahActionPerformed
         String Get_nip = nip.getText();
    String sql = "select * from kepalasekolah where nip='"+Get_nip+"';";
    try {
        java.sql.Statement stat = conn.createStatement();
        ResultSet rs = stat.executeQuery(sql);

        if (rs.next()) {
            String nip = rs.getString("nip");
            String nama = rs.getString("nama");

            // Set user data session
            UserSession.set_nama(nama);

            JOptionPane.showMessageDialog(null, "Selamat datang "+ nama +" !");
            new petugas.laporan().setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "NIP tidak ditemukan");
        }
    } catch (SQLException e) {
        System.out.println(e);
    }
    }//GEN-LAST:event_submit_kepalasekolahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Petugas;
    private javax.swing.JPanel Siswa;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel kepalasekolah;
    private javax.swing.JTextField nip;
    private javax.swing.JTextField nisn;
    private javax.swing.JButton submit;
    private javax.swing.JButton submit_kepalasekolah;
    private javax.swing.JButton submit_siswa;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JTextField tuser;
    // End of variables declaration//GEN-END:variables
}
